### ISSUE TITLE
Layout Home

### ISSUE THREAD

**Issue by gabrielecolombo** [densitydesign/incommon#17]
- [x] Modificare layout home (aggiunta loghi e ridimensionamento menu) [mock-up](https://www.figma.com/proto/mCsLWSH5znjKYhjpWnEfpi/INCOMMON---Home---MAR2022?node-id=16%3A6&scaling=scale-down-width&page-id=0%3A1&starting-point-node-id=16%3A6)
- [x] Quando si clicca su una sezione il margin-top del testo dovrebbe rimanere uguale (adesso aumenta e quindi il testo si abbassa)
- [x] Manca freccia dopo explore [link al svg](https://drive.google.com/file/d/1DZLDAa989Np4r3G4w_hfbYoWQGK62Cap/view?usp=sharing)

**Comment by skaffo** [comment]
@gabrielecolombo ho inserito la freccia. In caso è ok chiudi pure.

**Comment by gabrielecolombo** [comment]
<img width="1792" alt="Schermata 2022-04-05 alle 17 14 56" src="https://user-images.githubusercontent.com/7290793/161786968-f2b8bb0f-4fb7-45cc-a961-2be6216b67c6.png">

ci sarebbe solo da allineare il div coi loghi a destra (ci ho provato ma non ci riesco)

**Comment by skaffo** [comment]
@gabrielecolombo fixato footer.
