### ISSUE TITLE
Pagina About

### ISSUE THREAD

**Issue by gabrielecolombo** [densitydesign/incommon#19]
Implementare pagina about [mockup qui](https://www.figma.com/file/mCsLWSH5znjKYhjpWnEfpi/INCOMMON---Home---MAR2022?node-id=0%3A1)

- sul click all'immagine in alto si aprirà un video (caricato su vimeo)
- se impostate il testo sotto poi aggiungo io i testi delle bio

**Comment by skaffo** [comment]
@gabrielecolombo  una volta all'interno della pagina about come torno nelle altre pagine?

**Comment by gabrielecolombo** [comment]
cliccando su tutta la parte in alto con il logo
<img width="1792" alt="Schermata 2022-03-30 alle 14 10 25" src="https://user-images.githubusercontent.com/7290793/160832027-02440958-946a-4f7a-8e4f-31727b59f917.png">

[](https://www.figma.com/proto/mCsLWSH5znjKYhjpWnEfpi/INCOMMON---Home---MAR2022?node-id=62%3A254&scaling=scale-down-width&page-id=0%3A1&starting-point-node-id=16%3A6
)

**Comment by gabrielecolombo** [comment]
[animazione qui](https://www.figma.com/proto/mCsLWSH5znjKYhjpWnEfpi/INCOMMON---Home---MAR2022?node-id=62%3A254&scaling=scale-down-width&page-id=0%3A1&starting-point-node-id=16%3A6)
