### ISSUE TITLE
API Documenti

### ISSUE THREAD

**Issue by gffuma** [densitydesign/incommon#2]
Di seguito lascio un idea delle API.
I nomi dei campi sono quelli del frontend per chiarezza poi non sarà un problema avere i campi previsti nell applicativo attuale.

## Catalogo dei documenti

`/api/documents`

Parametri:

- Pagination Es:. `?page=`
- Search Es:. `?q=` full text search sui documenti
- Tipologia: `?tipologia=` filtra per tipologia
- Evento: `?evento=` filtra per evento
- Spettacolo: `?spettacolo=` filtra per spettacolo
- Luogo: `?luogo=` filtra per luogo
- Citta: `?citta=` filtra per citta
- Data: `?data=` filtra per data
- Anno: `?anno=` filtra per anno
- Persona: `?persona=` filtra per persona
- Compagnia: `?compagnia=` filtra per compagnia
- Organizzazione: `?organizzazione=` filtra per organizzazione
- Rivista: `?rivista=` filtra per rivista

NB
Tutti i filtri a parte search devono avere la possibilità di essere applicati
in OR:

Filtra per _tipo1_ e _tipo2_

`?tipologia=tipo1&tipologia=tipo2`

Risposta:

```json
{
  "count": 1274,
  "next": "...?page=3",
  "previous": "...?page=1",
  "results": [
    {
      "id": 23,
      "tipologia": "Tipologia",
      "evento": "Evento",
      "spettacolo": "Spettacolo",
      "luogo": "Luogo",
      "citta": "Citta",
      "data": "Data",
      "anno": "Anno",
      "persona": "Persona",
      "compagnia": "Compagnia",
      "organizzazione": "Organizzazione",
      "rivista": "Rivista",
      "images": [
        {
          "id": 420,
          "image": "http://myimage/doc-420.png"
        },
        {
          "id": 46,
          "image": "http://myimage/doc-46.png"
        }
      ]
    }
  ]
}
```

NB Raggruppa per documenti potrebbe essere implementato lato client.

API per disegnare i count.

`/api/documents/count`

```json
{
  "count": 1247,
  "countBy": {
    "tipologia": [
      {
        "name": "tipo1",
        "count": 29
      },
      {
        "name": "tipo2",
        "count": 102
      }
    ],
    "evento": [
      {
        "name": "tipo1",
        "count": 29
      },
      {
        "name": "tipo2",
        "count": 102
      }
    ],
    "spettacolo": [
      {
        "name": "tipo1",
        "count": 29
      },
      {
        "name": "tipo2",
        "count": 102
      }
    ],
    "luogo": [
      {
        "name": "tipo1",
        "count": 29
      },
      {
        "name": "tipo2",
        "count": 102
      }
    ],
    "citta": [
      {
        "name": "tipo1",
        "count": 29
      },
      {
        "name": "tipo2",
        "count": 102
      }
    ],
    "data": [
      {
        "name": "tipo1",
        "count": 29
      },
      {
        "name": "tipo2",
        "count": 102
      }
    ],
    "anno": [
      {
        "name": "tipo1",
        "count": 29
      },
      {
        "name": "tipo2",
        "count": 102
      }
    ],
    "persona": [
      {
        "name": "tipo1",
        "count": 29
      },
      {
        "name": "tipo2",
        "count": 102
      }
    ],
    "compagnia": [
      {
        "name": "tipo1",
        "count": 29
      },
      {
        "name": "tipo2",
        "count": 102
      }
    ],
    "organizzazione": [
      {
        "name": "tipo1",
        "count": 29
      },
      {
        "name": "tipo2",
        "count": 102
      }
    ],
    "rivista": [
      {
        "name": "tipo1",
        "count": 29
      },
      {
        "name": "tipo2",
        "count": 102
      }
    ]
  }
}
```

## Dettaglio documento

`/api/documents/23`

```json
{
  "id": 23,
  "tipologia": "Tipologia",
  "evento": "Evento",
  "spettacolo": "Spettacolo",
  "luogo": "Luogo",
  "citta": "Citta",
  "data": "Data",
  "anno": "Anno",
  "persona": "Persona",
  "compagnia": "Compagnia",
  "organizzazione": "Organizzazione",
  "rivista": "Rivista",
  "images": [
    {
      "id": 420,
      "image": "http://myimage/doc-420.png"
    },
    {
      "id": 46,
      "image": "http://myimage/doc-46.png"
    }
  ]
}
```

**Comment by skaffo** [comment]
@ccris77 Ciao Cristiano ho notato che ci sono delle preview non funzionanti ti cito un esempio qui sotto:

`{
                    "id": "289969C0-D318-11EA-88EC-4FC698E5D6FD/GC0036 (1).jpg",
                    "preview": "https://archivio.in-common.org/preview/289969C0-D318-11EA-88EC-4FC698E5D6FD/GC0036 (1).jpg/preview.png",
                    "image": "https://archivio.in-common.org/cdn/289969C0-D318-11EA-88EC-4FC698E5D6FD/GC0036 (1).jpg"
                },` 

In questo caso la preview dell'immagine ritorna un not found. (Vedi allegato)

![244C4909-43B0-41B2-AE16-3921AF9084BA](https://user-images.githubusercontent.com/16683586/103275195-ebe47380-49c3-11eb-9fe7-747f12c42431.jpeg)

**Comment by ccris77** [comment]
un piccola regressione con gli spazi, ho sistemato
