### ISSUE TITLE
Performance remains - implementare vista

### ISSUE THREAD

**Issue by gabrielecolombo** [densitydesign/incommon#23]
Implementare vista secondo [vecchio mock-up](https://xd.adobe.com/view/5c43c2e7-44e5-4648-5cb4-19e1a4078e00-2a72/?fullscreen)  con queste differenze: 

- Il pulsante “mostra annotazioni” non c’è più
- “Filtra per collezione” diventa solo “Filter:”
- “Mostra tutte le collezioni” diventa “Show all images”
- qua [c'è un mock-up interattivo di esplorazione delle immagini ](https://aquaalta.densitydesign.org/output/index.html )

**Comment by gffuma** [comment]
Ciao @gabrielecolombo la pagina performance remains dovrebbe essere a posto

**Comment by gabrielecolombo** [comment]
che bomba perfetto grazie. solo queste quattro cose:

- [ ] alla prima apertura appare il box con la spiegazione che andrebbe disattivato
- [ ] Filtro attivo e disattivo ora diventa rosso —> si può fare come nella vista recomposition in cui rimane bianco e gli altri grigi?
- [ ] Ce ne sono 7 senza archivio —> invece che vuoto si può scrivere “Unknown archive”
- [ ] Quando si clicca su un doc e si apre la scheda documento l’immagine non è centrata (si centra poi al primo click). Si può fare che si apre direttamente centrata? (Questo mi sembra che succeda sempre in generale nella scheda documento)

**Comment by gffuma** [comment]
Il problema del doc non centra con questa vista quindi chiudo questa issue.
