### ISSUE TITLE
Recomposition - pagina singolo caso studio | modifiche

### ISSUE THREAD

**Issue by gabrielecolombo** [densitydesign/incommon#25]
Modifiche alla pagina del singolo caso studio [mock up è qui](https://www.figma.com/proto/yzy3dFM3pJ0PDiD6nMSaVX/recomposition---03-2022?node-id=2%3A2&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=2%3A2) - [figma editabile qui](https://www.figma.com/file/yzy3dFM3pJ0PDiD6nMSaVX/recomposition---03-2022?node-id=2%3A2)

- [x] lo slideshow si apre cliccando sul pulsante “watch slideshow”  (invece che cliccare su un mucchietto come succede adesso)
- [x] Cliccando su un mucchietto si va invece alla pagina del catalogo filtrato con quei documenti
- [x] Cliccando su “read more”, si apre la pagina con il testo 
- [x] Nello slideshow manca il bottone che porta alla scheda del documento (vedi mock-up) con scritto "open document file"
- [x] All’apertura della pagina caso studio, si deve vedere il mucchietto totale (ora è vuoto)
- [x] Lo slideshow deve ricominciare da 1 quando arriva alla fine delle immagini

**Comment by skaffo** [comment]
@gabrielecolombo per questo punto: Nello slideshow manca il bottone che porta alla scheda del documento (vedi mock-up) con scritto "open document file". Servirebbe l'ID del documento nella configurazione dello slideshow.

**Comment by gabrielecolombo** [comment]
@skaffo[ i testi di descrizione sono qui (ita e eng).](https://docs.google.com/document/d/1OqbkDANlnRpQAstLwUtX71kLPr0-Xs672-6o5w0DTNY/edit?usp=sharing) nel caso se fai le pagine (e file dove mettere i testi) poi li copio io a mano.

**Comment by skaffo** [comment]
ciao @gabrielecolombo devo fare una pagina apposita per ogni spettacolo? ora ho messo un div in absolute che copre il contenuto sotto. I vari testi li ho messi direttamente nel file caseStudies.js in description e description_en

**Comment by gabrielecolombo** [comment]
va benissimo così, i testi li aggiungo io nel file caseStudies.js
L'uniche cose sul layout 

- l'img a dx dovrebbe sempre occupare il 50% senza margina a destra
- il testo sulla sinistra invece dovrebbe scrollare in basso (quando è troppo lungo)
- mentre l'immagine a destra sta ferma quando la parte di sx col testo scrolla in giù
- mancano i due EN e IT a sinistra del testo

(mi sa che ho fatto casino modificando il file casestudies.js)

**Comment by skaffo** [comment]
@gabrielecolombo testi li ho aggiunti io. Ok procedo alle altre modifiche.

**Comment by skaffo** [comment]
@gabrielecolombo ho fixato scontri generali. Mancano solo i filtri.

**Comment by gabrielecolombo** [comment]
ho visto perfetto
aspettiamo per i filtri la mail
