### ISSUE TITLE
Recomposition - bugs casi studio

### ISSUE THREAD

**Issue by gabrielecolombo** [densitydesign/incommon#29]
- [x] - Alcuni casi studio segnano 0 documenti (ma qui ci sono: https://archivio.in-common.org/api/casestudy) 

- [x] - in altri, il numero di documenti è giusto ma poi dentro al caso studio le immagini sono rotte (ma qui funzionano:  https://archivio.in-common.org/api/casestudy) Ad esempio: Sir & Lady Macbeth e Assoli

<img width="1234" alt="Schermata 2022-03-30 alle 12 07 37" src="https://user-images.githubusercontent.com/7290793/160807264-f248e6d0-c40d-4eab-921d-b2d1694b817a.png">

**Comment by skaffo** [comment]
@gabrielecolombo ho verificato anche qui utilizziamo le preview delle immagini e non le image stesse in quanto troppo pesanti. I casi invece che segnano documenti molto probabilmente il nome presente in titolo nel JSON non è strettamente uguale a quello dei dati da api esempio: Titolo tuo da json: Festival di Beckett, Titolo da api: Festival di S. Beckett
Se metti il titolo corretto i documenti verranno automaticamente associati.

**Comment by gabrielecolombo** [comment]
ok sistemato i titoli grazie
e si ho controllato e sono le preview rotte

invece ho notato che quando ci sono tanti documenti non riesce a caricare il caso studio
ad esempio:
http://localhost:3000/recomposition/scontri-generali

**Comment by skaffo** [comment]
@gabrielecolombo per questa pagina meglio parlarne nel pomeriggio insieme. In questo singolo casi di scontri generali caricando tantissime immagini si blocca tutto. Inoltre c'è da ragionare sui links che portano poi ai documenti.

**Comment by gabrielecolombo** [comment]
ok va bene ne parliamo dopo

**Comment by gabrielecolombo** [comment]
@skaffo 
non so se può aiutare ma mandano la mail a loro mi sono accorto di questa cosa
aggiungendo lo slash alla fine cambia il numero (il caso è quello che ho scritto nella mail: foto B/N + "Luci della città")

https://archivio.in-common.org/api/documents?spettacolo=Luci%20della%20citt%C3%A0&tipologia=Fotografia%20b%2Fn/
https://archivio.in-common.org/api/documents?spettacolo=Luci%20della%20citt%C3%A0&tipologia=Fotografia%20b%2Fn
