### ISSUE TITLE
Scheda documento - modifiche al layout

### ISSUE THREAD

**Issue by gabrielecolombo** [densitydesign/incommon#31]
- [x] Su schermi piccoli, e quando c’è molto testo di descrizione, non si riesce a scrollare fino in fondo i campi dei filtri. Ad esempio: [questo documento](https://incommon.sandbox.inmagik.com/catalogue/GC0066 )
- [x] Il testo di descrizione dovrebbe mantenere gli a capo (al momento non li tiene).
- [x] zoom del documento dovrebbe usare tutto lo spazio (ora il div non arriva fino al fondo -- vedi immagine)
- [x] Nei documenti multipli: Implementare la possibilità di andare avanti e indietro con **Frecce dx e sx**
- [x] Nei documenti multipli: Implementare la possibilità di andare avanti e indietro con **Click sulla zona sx e dx dello spazio**
 
<img width="1792" alt="Schermata 2022-03-30 alle 12 23 52" src="https://user-images.githubusercontent.com/7290793/160811102-8cc27919-663a-48b8-88db-33d9f8eb3b54.png">

**Comment by gabrielecolombo** [comment]
ah ora ho visto che funziona 
però rimane dentro un mini div della dimensione della foto
dovrebbe andare full screen

<img width="1785" alt="Schermata 2022-04-05 alle 17 23 19" src="https://user-images.githubusercontent.com/7290793/161788757-3d222def-9a30-441e-91da-f18c88eada46.png">

**Comment by skaffo** [comment]
@gabrielecolombo prova a aggiornare stai usando chrome?

**Comment by skaffo** [comment]
@gabrielecolombo puoi verificare che ho modificato il plugin?

**Comment by gabrielecolombo** [comment]
Adesso lo zoom funziona
però 

- all'inizio, quando si apre la pagina, l'immagine dovrebbe partire dalla sua dimensione normale (ora parte già zoomata con l'immagine che occupa tutto lo spazio)
- lo spazio dove zooma ora copre la barra sopra dove ci sono i comandi, questo div: `<div class="header-images d-flex justify-content-between">` Dovrebbe arrivare fino a sotto senza coprirlo

<img width="1791" alt="Schermata 2022-04-06 alle 12 02 00" src="https://user-images.githubusercontent.com/7290793/161951384-6507c5b9-38c2-4123-b640-2f253b41f671.png">

**Comment by gabrielecolombo** [comment]
comunque strano, sulla maggior parte funziona, su altre si comporta come prima (usa solo lo spazio dell'immagine)
ad esempio
questo
http://localhost:3000/catalogue/EP0044

**Comment by skaffo** [comment]
@gabrielecolombo https://incommon.sandbox.inmagik.com/catalogue/EP0044 anche online si comporta uguale?

**Comment by skaffo** [comment]
@gabrielecolombo secondo me devi fare yarn install in locale xk ho aggiornato il pacchetto.

**Comment by gabrielecolombo** [comment]
yep ora funziona
grazie
