### ISSUE TITLE
The shape of community - modifiche layout

### ISSUE THREAD

**Issue by gabrielecolombo** [densitydesign/incommon#34]
- [x] Implementare click sul nodo → si apre il pannello con dati sul nodo (o se è già aperto cambia) | [mock up qui ](https://xd.adobe.com/view/d33098ff-ca9d-4084-bce0-938418e19330-8663/?fullscreen) (per ora funziona solo con il search ma non con il click sul nodo)
- [x] Quando un nodo è selezionato togliere il comportamento che diventa giallo
- [x] Implementare interazione su nodo all hover  → rimane visibile il nodo, gli edges e i nodi collegati, e tutto il resto diventa meno visibile = opacity 0.5)
- [x] Risolvere problema anti-aliasing

**Comment by skaffo** [comment]
@gabrielecolombo inserito click al nodo in caso è ok chiudi pure.

**Comment by gabrielecolombo** [comment]
ho visto perfetto.
L'ultima cosa (giuro): ma non è che si può settare che dopo un tot di tempo si ferma la spazializzazione?
perchè già lo fa al click su un nodo magari si riesce a fare anche in generale dopo un tot di tempo?
(che alcuni cluster continuano a volare via all'esterno)

**Comment by skaffo** [comment]
@gabrielecolombo posso fare in modo che dopo tot secondi si blocchi la spazializzazione. Ora ho impostato 15 secondi fammi sapere come è.

**Comment by gabrielecolombo** [comment]
il tempo va bene, però dovrebbe ripartire quando selezioni un filtro se no succedono queste cose (la rete non è spazializzata)
Se non si riesce a farlo ripartire (e poi stoppare dopo 10 seco) meglio che si muova sempre

<img width="1792" alt="Schermata 2022-04-07 alle 11 17 20" src="https://user-images.githubusercontent.com/7290793/162165891-5012e148-d586-4af0-b58d-ff8fb440f5d6.png">

**Comment by skaffo** [comment]
@gabrielecolombo prova ora ho pushato una modifica che riattiva la spazializzazione per 15 secondi dopo aver disattivato attivato un filtro.

**Comment by gabrielecolombo** [comment]
mi sembra siano meno quando lo riattivi
tipo clicco su Curating e poi lo riclicco si muove per meno di 15 secondi e non fa tempo a spazializzarsi bene

**Comment by skaffo** [comment]
@gabrielecolombo ho fatto un ultima prova allungando il tempo. fammi sapere se no lo rendo sempre in movimento.

**Comment by gabrielecolombo** [comment]
va bene perfetto chiudo
