### ISSUE TITLE
The shape of community - bug

### ISSUE THREAD

**Issue by gabrielecolombo** [densitydesign/incommon#35]
quando si zooma la rete e poi clicco sul pulsante per centrare, succede questo
<img width="1416" alt="Schermata 2022-03-30 alle 10 45 42" src="https://user-images.githubusercontent.com/7290793/160815522-fb7c2031-5999-4842-8b50-a6871cfb33db.png">

**Comment by skaffo** [comment]
@gabrielecolombo dovrei aver fixato il bug.
