### ISSUE TITLE
Times and Places - modifica dati

### ISSUE THREAD

**Issue by gabrielecolombo** [densitydesign/incommon#36]
Aggiungere i dati dei luoghi dell’archivio  [questi](https://archivio.in-common.org/api/spettacoli) a quelli che ci sono già nel json `src/data/network-luoghi.json`

Anche questa vista poi non sarà più aggiornabile (come la rete)

**Comment by skaffo** [comment]
@gabrielecolombo questa vista già aggrega i dati da api.

**Comment by gabrielecolombo** [comment]
ok a posto sistemo le coordinate sbagliate direttamente nel json allora
ho notato però che quando il campo luogo è vuoto 
non fa vedere neanche il campo evento - ad esempio questa: 

`  {
    "anno": "1968",
    "citta": "Carpi",
    "luogo": "",
    "evento": "Gli uccelli [Cobelli '68]",
    "coords": [
      {
        "formattedAddress": "41012 Carpi MO, Italy",
        "latitude": 44.7838779,
        "longitude": 10.8796629,
        "extra": {
          "googlePlaceId": "ChIJowIQoy2Nf0cRP8YZ9V89seM",
          "confidence": 0.5,
          "premise": null,
          "subpremise": null,
          "neighborhood": "Carpi",
          "establishment": null
        },
        "administrativeLevels": {
          "level3long": "Carpi",
          "level3short": "Carpi",
          "level2long": "Provincia di Modena",
          "level2short": "MO",
          "level1long": "Emilia-Romagna",
          "level1short": "Emilia-Romagna"
        },
        "city": "Carpi",
        "country": "Italy",
        "countryCode": "IT",
        "zipcode": "41012",
        "provider": "google"
      }
    ]
  },`
<img width="1781" alt="Schermata 2022-03-31 alle 12 34 21" src="https://user-images.githubusercontent.com/7290793/161036571-c2608532-7a25-47e1-8bc2-593ca932be3b.png">

**Comment by skaffo** [comment]
@gabrielecolombo yes perchè checkavo che il luogo fosse obbligatorio. Ora ho fixato e viene mostrato in ogni caso il nome dell'evento.

**Comment by gabrielecolombo** [comment]
perfetto grazie
