### ISSUE TITLE
Traduzione 

### ISSUE THREAD

**Issue by gabrielecolombo** [densitydesign/incommon#39]
Implementare traduzione [secondo questo dizionario ](https://docs.google.com/spreadsheets/d/1oxI5zRbO7bu1n7eTMS_zd1OnlkajYSe_XJ_xlQSG-6U/edit#gid=0)

Come facciamo (ci sarà qualcosa che sicuramente è sfuggito e lo devo tradurre)?

**Comment by gabrielecolombo** [comment]
@skaffo ho caricato un json con le traduzioni dentro data
vedi se va bene così

**Comment by skaffo** [comment]
@gabrielecolombo l'ho modificato un attimo e inserito nella pagina catalogo e spettacolo dettaglio.

**Comment by gabrielecolombo** [comment]
perfetto, questa la chiudo
