### ISSUE TITLE
Devices

### ISSUE THREAD

**Issue by gabrielecolombo** [densitydesign/incommon#40]
- [ ] preparare mock-up per messaggio che dice: No telefono e Gira in orizzontale
- [ ] implementare

**Comment by skaffo** [comment]
@gabrielecolombo pushato una versione.

**Comment by gabrielecolombo** [comment]
va bene 
adesso si attiva da 768 
forse lo farei partire già da prima
tipo 820?

**Comment by skaffo** [comment]
@gabrielecolombo impostato a 820.
