### ISSUE TITLE
Recomposition - info panel

### ISSUE THREAD

**Issue by gabrielecolombo** [densitydesign/incommon#46]
Quando si scrolla in basso il pannello info si vede la seconda parte delle thumbnails sotto
bisognerebbe disattivarlo
(succede solo in questa vista)

<img width="1466" alt="Schermata 2022-04-06 alle 14 52 37" src="https://user-images.githubusercontent.com/7290793/161980182-3f014e50-08f3-4200-945a-da59e0882aec.png">

**Comment by skaffo** [comment]
@gabrielecolombo fixato
