### ISSUE TITLE
Loading page

### ISSUE THREAD

**Issue by gabrielecolombo** [densitydesign/incommon#47]
https://www.figma.com/proto/itVlWrHq8PBSQYFpZKcgpo/INCOMMON---Home?node-id=304%3A173&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=16%3A6

**Comment by skaffo** [comment]
@gabrielecolombo da inserire dove?

**Comment by gabrielecolombo** [comment]
ma pensavo per quando non si caricano le cose 
ma forse non serve lasciamo stare
