### ISSUE TITLE
media queries

### ISSUE THREAD

**Issue by gabrielecolombo** [densitydesign/incommon#48]
**Home**
- [x] testo  e dimensione boxes

- [x] immagini quando il div è aperto

<img width="300" alt="Schermata 2022-04-07 alle 15 22 27" src="https://user-images.githubusercontent.com/7290793/162208908-03a93a41-728e-4055-89cd-b10a62bb8c11.png">
 
**Footer**
- [x] loghi
- [x] testo ERC più piccolo

**Recomposition**

- [x] thumbnails testo più piccolo 
<img width="300" alt="Schermata 2022-04-07 alle 15 27 14" src="https://user-images.githubusercontent.com/7290793/162209718-29ccb497-e037-4a0a-b247-f4c61a5799b6.png">

- [x] caso studio titolo più piccolo 
- [x] caso studio eliminare icone 
<img width="253" alt="Schermata 2022-04-07 alle 15 27 58" src="https://user-images.githubusercontent.com/7290793/162210145-96498eb4-e1a4-40b4-8291-44edb31985f6.png">

- [x] testo read more più piccolo

<img width="400" alt="Schermata 2022-04-07 alle 15 29 42" src="https://user-images.githubusercontent.com/7290793/162210342-cc358b23-5226-49af-b62b-0983032a48e1.png">

- [x] pannello coi filtri dovrebbe essere scrollabile (come quello del catalogo)

<img width="265" alt="Schermata 2022-04-07 alle 15 31 02" src="https://user-images.githubusercontent.com/7290793/162210716-7b52f570-0e16-471d-9f2b-6ccb9f74692e.png">

**Times and places**

- [x] pannello dovrebbe essere più largo perchè si taglia la line chart 
<img width="400" alt="Schermata 2022-04-07 alle 15 34 03" src="https://user-images.githubusercontent.com/7290793/162211590-1390b0d7-615a-42b0-a9d1-919dbfd699d3.png">

**Catalogue**

- [x] togliere icone filtri
<img width="286" alt="Schermata 2022-04-07 alle 15 39 41" src="https://user-images.githubusercontent.com/7290793/162212522-11d8b40b-9bcb-41e3-9c63-d858c339a32c.png">

**Pannelli Info**

- [x] ridurre margine dx e sx
<img width="798" alt="Schermata 2022-04-07 alle 15 41 37" src="https://user-images.githubusercontent.com/7290793/162212927-bb7bfc4e-29f6-44c3-ab8e-5c552eb76df2.png">

**Comment by skaffo** [comment]
@gabrielecolombo ok per questi due pannello coi filtri dovrebbe essere scrollabile (come quello del catalogo)
pannello dovrebbe essere più largo perchè si taglia la line chart. Per quanto riguarda il problema nella home non riesco a replicarlo in quali risoluzioni?

**Comment by gabrielecolombo** [comment]
@skaffo in realtà lo fa un po' sempre anche quando lo schermo è grande (forse sono stato io perchè ho cambiato l'altezza che prima era max-content e ora è in px?)

```
.page-home-open {
  border-top: 1px solid #ffffff;
  display: flex;
  cursor: pointer;
  height: 501px;
  transition: height ease-out 0.5s;

}
```
<img width="1904" alt="Schermata 2022-04-07 alle 16 54 36" src="https://user-images.githubusercontent.com/7290793/162229195-182dc326-37b0-4465-b297-33c9bc1b4d31.png">

**Comment by skaffo** [comment]
@gabrielecolombo ho messo le immagini come background cover. Fammi sapere se ci stanno cosi.

**Comment by gabrielecolombo** [comment]
@skaffo perfetto così si ingrandiscono anche quando si apre, ora metto le immagine giuste. 
Mi riesci a dare una mano anche col footer? (sono riuscito a sistemare un po' ma mi mancano due cose)

- **da 1200 a 1400** il testo "This project has received funding from the European Research Council (ERC) under the European Union's Horizon 2020 research and innovation programme (grant agreement No 678711)" dovrebbe andare sotto il logo dell'europa, largo quanto l'immagine. E il logo allineato in alto (non `align-items: center `)
![Schermata-2022-04-08-alle-10 21 11](https://user-images.githubusercontent.com/7290793/162396929-a8336bb8-27fe-4404-9e2a-e86254d3d22f.jpg)

- **sotto i 1200** il testo piccolo "The information and views set out in this website are those of the author(s) and do not necessarily reflect the official opinion of the European Union. Neither the European Union Institutions and bodies nor any person acting on their behalf may be held responsible for the use which may be made of the information contained therein." dovrebbe andare a destra del logo. I loghi sotto distribuiti su tutto la larghezza (non allineati a dx). Ho provato con `justify-content: space-around;`  ma non funziona 

![Schermata-2022-04-08-alle-10 21 11_3](https://user-images.githubusercontent.com/7290793/162397749-e7dfa54c-7e60-4279-9da2-2385a344bf5a.jpg)

**Comment by skaffo** [comment]
@gabrielecolombo pushato. In caso vuoi piu spaziature lavora sui pl-xl- pl-lg
