### ISSUE TITLE
API Case Study

### ISSUE THREAD

**Issue by gffuma** [densitydesign/incommon#5]
## Lista Case Studies

Titolo e campi relativi.

## Dettaglio Case Study

Titolo, campi relativi e le seguenti relazioni:
- Lista Date
- Lista Luoghi
- Lista Città 
- Lista Persone
- Lista immagini con relativi metadati (tipologia, archivio)

**Comment by ccris77** [comment]
l'api è già disponibile all'entry point /api/casestudy

**Comment by skaffo** [comment]
@ccris77 Ciao Cristiano ho provato l'api con l'url che mi hai indicato ma mi dice entrypoint non trovata come da allegato.
https://archivio.in-common.org/api/casestudy

![59FB6679-5D92-446D-84AD-69BBBC1EDDD8](https://user-images.githubusercontent.com/16683586/103274517-2e0cb580-49c2-11eb-969a-c8e7ea277cd6.jpeg)
