### ISSUE TITLE
Schede documento che non si aprono da slideshow

### ISSUE THREAD

**Issue by gabrielecolombo** [densitydesign/incommon#55]
Alcune schede non si aprono cliccando su "open document file" dallo slideshow. 
facendo un po' di prove mi sembra che riguardi solo i documenti multipli (con più pagine)

esempio 1
- https://incommon.sandbox.inmagik.com/recomposition/edoardo-2/slideshow (immagine 11/40)
- https://incommon.sandbox.inmagik.com/catalogue/PD0117_01

esempio 2
- https://incommon.sandbox.inmagik.com/recomposition/edoardo-2/slideshow (immagine 21/40)
- https://incommon.sandbox.inmagik.com/catalogue/PD0115_07

esempio 3
- https://incommon.sandbox.inmagik.com/recomposition/festival-di-s-beckett/slideshow (immagine 14/19) e (immagine 15/19)
- https://incommon.sandbox.inmagik.com/catalogue/MG0023_01

**Comment by skaffo** [comment]
@gabrielecolombo ho fixato il problema. Unica cosa il primo esempio non carica proprio l'immagine.

**Comment by gabrielecolombo** [comment]
qua però mi sembra che ora non vanno più proprio ad esempio se provi questo caso studio non ne trova più nessuna
https://incommon.sandbox.inmagik.com/recomposition/theatre/slideshow

**Comment by gabrielecolombo** [comment]
mi sa che hai levato tutto e lasciato solo il numero
ad esempio questa (prima immagine dello slideshow:  https://incommon.sandbox.inmagik.com/recomposition/theatre/slideshow)

apre questo link 
https://incommon.sandbox.inmagik.com/catalogue/0154
ma dovrebbe andare qua
https://incommon.sandbox.inmagik.com/catalogue/GC0154

**Comment by skaffo** [comment]
@gabrielecolombo problema trovato. Noi in base al nome della foto che di solito è l'ID del documento costuiamo l'url in questo caso non so per quale motivo il nome dell'immagine è differente dall'ID https://archivio.in-common.org/cdn/CA5F7390-282B-11EB-AF05-B3E59852058F/0154.jpg

**Comment by gabrielecolombo** [comment]
le ho controllate tutte:

- dalla 1 alla 14, basta aggiungere "GC" davanti e funziona (magari si può aggiungere come eccezione?)
- 15,16, 17 puntano tutte allo stesso documento che è GC0153 (ma c'è un problema di spazi per quello non lo carica)
- 17 e 18 sono la stessa immagine e anche questa basta aggiungere GC davanti 

tipo http://localhost:3000/catalogue/0169 diventa http://localhost:3000/catalogue/GC0169

@skaffo 

dimmi te se si può fare solo per questo (perchè se no proprio non ne va neanche una)
se ti è più semplice posso fare una specie di json con url sbagliato e url nuovo (se me lo imposti lo compilo io a mano)

**Comment by skaffo** [comment]
@gabrielecolombo ho fatto eccezione per questo slideshow. fammi sapere e in caso chiudi issue.

**Comment by gabrielecolombo** [comment]
perfetto grazie mille @skaffo 
chiudo
