### ISSUE TITLE
Catalogo: thumbnail ruotate di 180

### ISSUE THREAD

**Issue by gabrielecolombo** [densitydesign/incommon#56]
nel catalogo ci sono un po' di thumbnails che vengono visualizzate ruotate di 180 (poi nella scheda sono corrette)
qua un po' di esempi

https://incommon.sandbox.inmagik.com/catalogue/MG0125
https://incommon.sandbox.inmagik.com/catalogue/MG0150
https://incommon.sandbox.inmagik.com/catalogue/MG0129
https://incommon.sandbox.inmagik.com/catalogue/MB0069
https://incommon.sandbox.inmagik.com/catalogue/MG0156
https://incommon.sandbox.inmagik.com/catalogue/MG0155
https://incommon.sandbox.inmagik.com/catalogue/MB0064
https://incommon.sandbox.inmagik.com/catalogue/MG0146
https://incommon.sandbox.inmagik.com/catalogue/MG0134
https://incommon.sandbox.inmagik.com/catalogue/ST0029
https://incommon.sandbox.inmagik.com/catalogue/MB0068
https://incommon.sandbox.inmagik.com/catalogue/MG0149
https://incommon.sandbox.inmagik.com/catalogue/MB0016
https://incommon.sandbox.inmagik.com/catalogue/MG0148
https://incommon.sandbox.inmagik.com/catalogue/GC0098
https://incommon.sandbox.inmagik.com/catalogue/GC0101
https://incommon.sandbox.inmagik.com/catalogue/MG0126
https://incommon.sandbox.inmagik.com/catalogue/MG0135
https://incommon.sandbox.inmagik.com/catalogue/ST0039
https://incommon.sandbox.inmagik.com/catalogue/MB0077
https://incommon.sandbox.inmagik.com/catalogue/MG0144
https://incommon.sandbox.inmagik.com/catalogue/MG0120
https://incommon.sandbox.inmagik.com/catalogue/MB0076)

**Comment by skaffo** [comment]
@gabrielecolombo da segnalare a Cristiano. Le preview vengono create da loro quindi non posso fare molto.

**Comment by gabrielecolombo** [comment]
cristiano
