### ISSUE TITLE
materiali video e audio

### ISSUE THREAD

**Issue by gabrielecolombo** [densitydesign/incommon#58]
ci sono materiali video e audio che non si caricano (ho scoperto adesso che ci sono)
ad esempio cortometraggi o autointerviste

http://localhost:3000/catalogue?tipologia=Cortometraggio 
http://localhost:3000/catalogue?tipologia=Autointervista

è un casino farle caricare? nel caso possiamo mostrare un icona nel catalogo e poi si apre audio o video nella scheda documento

**Comment by gabrielecolombo** [comment]
qua nel caso sia fattibile tecnicamente ti carico un icona per i video e una per gli audio da caricare
(però poi nella scheda documento bisogna capire se si riesce a mettere un player)
dimmi tu se non è troppo lungo implementare questa cosa

**Comment by skaffo** [comment]
@gabrielecolombo ho impostato i vari dettagli documenti sia per il video che per gli audio. ho creato un immagine placeholder che puoi sostituire per le previews placeholder-image.png in public che puoi cambiare. 

Esempio di Video: https://incommon.sandbox.inmagik.com/catalogue/MG0024
Esempio di Audio: https://incommon.sandbox.inmagik.com/catalogue/GC0035

**Comment by gabrielecolombo** [comment]
manca il pulsante per chiudere la scheda

<img width="1790" alt="Schermata 2022-05-09 alle 12 59 28" src="https://user-images.githubusercontent.com/7290793/167396726-2d68f081-10f2-48b0-8773-6c2e1553a3eb.png">

**Comment by skaffo** [comment]
@gabrielecolombo te lo metto io gabri?

**Comment by gabrielecolombo** [comment]
se riesci si, che ho provato ma ho fatto macello

**Comment by skaffo** [comment]
@gabrielecolombo ok pushato.
