### ISSUE TITLE
The shape of community - dividere le due reti

### ISSUE THREAD

**Issue by gabrielecolombo** [densitydesign/incommon#62]
Hanno segnalato che unire i due dataset crea dei problemi (dal loro punto di vista)

è molto complicato ridividere i due dataset 
e aggiungere un pulsante in basso a sx che permette di switchare da un dataset all'altro? 

le due reti rimarrebbero separate e mai sovrapponibili ma si può scegliere se caricare una rete o l'altra. 

nel caso non è troppo lungo 
faccio un mock-up del pulsante e ridivido di due dataset

**Comment by gabrielecolombo** [comment]
a questa cosa ci tengono abbastanza però dimmi tu visto che la rete so che è un po' macello metterci le mani

**Comment by skaffo** [comment]
@gabrielecolombo ho diviso le due reti. Fammi sapere la label da mettere per il cambio del dataset.

**Comment by gabrielecolombo** [comment]
ho visto che bomba grazie 

per il momento metti così. poi nel caso cambio io 
per caricare quella piccola: "show Incommon network"
per caricare quella grande: "show theatrographic network"
