### ISSUE TITLE
recomposition slideshow

### ISSUE THREAD

**Issue by gabrielecolombo** [densitydesign/incommon#66]
controllare che funzionino tutti

**Comment by gabrielecolombo** [comment]
https://incommon.sandbox.inmagik.com/recomposition/nostra-signora-dei-turchi

**Comment by gabrielecolombo** [comment]
- [ ] Edoardo II
- [ ] Festival di Beckett
- [ ] ZIP
- [ ] Nostra Signora dei Turchi
- [ ] Don Chisciotte
- [ ] Sir and Lady Macbeth
- [ ] Orlando Furioso
- [ ] Decentramento
- [ ] Scontri Generali
- [ ] Cenerella
- [ ] SUDD
- [ ] La rivolta degli oggetti
- [ ] Rotobolo
- [ ] Luci della città
- [ ] Cronache marziane
- [ ] Cottimisit
- [ ] Assoli
- [ ] Mors II
- [ ] Theatre Functions Terminated
- [ ] Theatre Functions Critical
- [ ] Theatre

**Comment by gabrielecolombo** [comment]
@skaffo ma mi spiegheresti come fare per sistemare i collegamenti tra slideshow e documento che non vanno (come hai fatto per lo slideshow che non funzionava)?
ho capito (credo) che devo modificare 
questo file `sparagmos/data/incommonImages.json `
(o questo? `sparagmos/data/incommonImagesMini.json`)

però non capisco cosa devo cambiare. Funziona così?

- dal json dello slideshow prendi l'url dell'immagine
- poi dentro a incommonImages.json lo colleghi a "LocalName" e a "docID"

però ho provato con questo  e mi sembra tutto giusto ma non va
`  {
    "id": "77E9CD90-24D4-11EB-8CC8-8BCD170BCFDC/MB0069.jpg",
    "content_provider": "Archivio Franco Quadri-UBU Libri,  c/o Fondazione Mondadori",
    "tipologia": "Fotografia b/n",
    "preview": "https://archivio.in-common.org/preview/77E9CD90-24D4-11EB-8CC8-8BCD170BCFDC/MB0069.jpg/preview.png",
    "image": "https://archivio.in-common.org/cdn/77E9CD90-24D4-11EB-8CC8-8BCD170BCFDC/MB0069.jpg",
    "docID": "MB0069",
    "localName": "77E9CD90-24D4-11EB-8CC8-8BCD170BCFDC__MB0069.jpg"
  },`

**Comment by skaffo** [comment]
ciao @gabrielecolombo no quei due json fanno riferimento allo sparagmos non c'entrano niente. Per costruire il link noi utilizziamo l'url che tu hai inserito per costruire i JSON. Esempio slideshow: http://localhost:3000/recomposition/zip/slideshow  
La prima immagine di questo slideshow ha questo indirizzo: https://archivio.in-common.org/cdn/47BAB360-E0C1-11EB-8FE2-0959CDE6A93B/image00111_b.png noi praticamente splittiamo l'estensione dell'immagine e utilizziamo solo image00111 che però in questo caso non corrisponde ad un id di un documento quindi non funziona.

Per l'altro slideshow "Theatre" avevo fatto un if apposta per ovviare questo problema.

La pagina è Slideshow.js

In caso non hai capito mettimi un meet che ci sentiamo al volo.

**Comment by gabrielecolombo** [comment]
ah ok grazie mille
credo di avercela fatta ho aggiunto un altro if sotto per la prima di quello slideshow e funziona
Ma posso andare avanti ad aggiungere if così ho se ne metto troppi poi fa casino?
se non vedi problemi mi sembra che posso risolvere da solo

```
  if (
    slug === 'zip' &&
    (docID === 'image00111')
  ) {
    docID = 'VF0055'
  }

```

**Comment by skaffo** [comment]
@gabrielecolombo tutti questi if logicamente non vanno benissimo perchè rallentano più sono. La soluzione migliore forse era mettere ID del documento in un altro campo quando hai creato i vari slideshow. Però se non sono tantissimi io adotterei questa soluzione.
